#!/bin/bash

ARG_NONE=0
ARG_HELP=1
ARG_FILES=2

scriptName=$(basename "$0")

function usage {
	cat << ENDUSAGE
	Usage $scriptName [-h] file
ENDUSAGE
}

function help {
	cat << ENDHELP
	Description
	Open the file in a browser.
		-h Print this message.
	
ENDHELP
}

arg=()

while [ $# -gt 0 ]
do
	case $1 in
		-h|--help)
			arg[ARG_HELP]="1"
			;;
		*)
			arg[ARG_FILES]=$1
			;;
	esac
	shift
done

if [ -n "${arg[ARG_HELP]}" ] ; then
	usage
	help
	exit 0 ;
fi

url="file://$(realpath ${arg[ARG_FILES]})"
firefox --new-window "$url"
exit 0;
